### ISSUE TITLE
You're on the right lines

### ISSUE THREAD

**Issue by hannahgooding** [halimahexe/Cat-Game#1]
https://github.com/halimahexe/Cat-Game/blob/8938c4128a7c4a4d0368d8cbdca9d8ca3ec60e97/game.js#L111-L112

`catPic` refers to a string, you need the element i.e. `image`

**Comment by halimahexe** [comment]
Ah gotcha, so if I target the SVG with a document.querySelector, I think that should work!

**Comment by halimahexe** [comment]
I did it - thanks for pointing out where I was going wrong!
