### ISSUE TITLE
I was just about to suggest this!

### ISSUE THREAD

**Issue by hannahgooding** [halimahexe/Cat-Game#2]
https://github.com/halimahexe/Cat-Game/blob/8938c4128a7c4a4d0368d8cbdca9d8ca3ec60e97/game.js#L133

Yes to avoid repetition this should be a wrapper function around your other functions

**Comment by halimahexe** [comment]
Ooh, thanks for the suggestion. I'll have a think for how to make that work!

**Comment by hannahgooding** [comment]
Just seen your function that you've commented out at the bottom, seeing if I can see why it's not working...

**Comment by halimahexe** [comment]
I was trying to use an if statement that would redirect to the noActions function if (actions === 0) but it didn't seem to execute the function.

Ideally, though, I want to immediately show the option to end the day once actions hit 0 without needing to press a button first 🤔

**Comment by hannahgooding** [comment]
☝️ to execute that logic, think about what the script would need to "listen" to in order to trigger checking if there are no more actions allowed...

**Comment by hannahgooding** [comment]
RE: the original issue here, not 100% sure how you were trying to run it but think about what `i` is meant to refer to here:

https://github.com/halimahexe/Cat-Game/blob/8938c4128a7c4a4d0368d8cbdca9d8ca3ec60e97/game.js#L278

**Comment by halimahexe** [comment]
I managed to refactor so now every function points to noActions() if actions === 0. But couldn't figure out how to universalise the if (actions > 0) statement, so it's repeated in each function for now.

**Comment by halimahexe** [comment]
I managed to figure it out! I had to add () at the end of line 85 to ensure I was running the function
