### ISSUE TITLE
Use an object for readability

### ISSUE THREAD

**Issue by hannahgooding** [halimahexe/Cat-Game#4]
It can get confusing to know what these indexes are referring to in the lists

https://github.com/halimahexe/Cat-Game/blob/8938c4128a7c4a4d0368d8cbdca9d8ca3ec60e97/game.js#L119

I'd consider a different data structure like an object with keys which have more meaningful names e.g.

```javascript
const cats = [{
    ...
    points: { "feed" : 25, "pet": 10, "play": 15, "care": 5 },
    ...
},
```

This could also simplify your code for the other things you are trying to do...

**Comment by halimahexe** [comment]
Thank you, that makes a lot of sense!
